CREATE DATABASE EMPRESA 
GO 

USE EMPRESA
GO

CREATE TABLE PESSOA(
idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
nomePessoa VARCHAR(150) NOT NULL
);
GO 

CREATE TABLE TELEFONE(
IdTelefone SMALLINT PRIMARY KEY IDENTITY(1,1),
idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
numeroTelefone VARCHAR(20) NOT NULL UNIQUE
);
GO